- scope3_methodology/adtech_model.py
- scope3_methodology/compute_defaults.py
- scope3_methodology/corporate.py
- scope3_methodology/publisher.py
According to PEP8: Class names must follow CamelCase naming (Each new word is capitalized without underscore)
According to PEP8, function and variable names should be lowercase with words separated by underscores. In PYLEECAN, small exceptions are made to this rule: a method or a variable name can have capitalized letter if and only if it follows physical quantities (radius=R, number=N or Z, length=L etc). For instance, Zs is used for the number of slots or Rbo for the lamination bore radius.
> Fix styling

- scope3_methodology/cli/compute_defaults.py
So this happened because we had 
```
---
template:
name: generic
template: generic 
type: organization
```
and we added 
```
---
template:
name: generic
template: generic
type: property
```
So the name was the same, so when building the compute defaults we override the templates key. So we stopped computing defaults for `generic` organization. 
Update: the key is now on the combination of `name-type` which should always be a unique pairing. We should never have 2 templates of the same name and same type. 
This is the quick fix further updates needed:
- Add in tests for the computed files so that we a user is aware when they change computed files and can verify the change 
- Validation check on PR to prevent multiple templates being merged with the same name-type combination
> fix compute defaults with overlapping template names

- scope3_methodology/api/api.py
It was confusing why it was always null, and the is a nested object within an object. So this is cleanest and easiest way to return for now. This is also a very simple API, so erring on the side of not returning more data than needed
> remove defaults from api parse corporate file response 

- scope3_methodology/end_user_device/model.py
- scope3_methodology/test/test_end_user_device_model.py
Exposing these new model fields for creative usage.
For production creative:  we have production grams per second which we can then do `production_g_per_second` * `creative_s` = `gco2e` emissions  
For device emissions of playing the ads we use `power_emissions_kwh_per_second` which we then do `power_emissions_kwh_per_second` * `creative_duration_s` * `gco2e_per_kwh` = `gco2e` emissions
> Add device emissions per second

- data/companies/rea_group/corporate.yaml
- data/companies/rea_group/property_data.yaml
- data/companies/theguardian/corporate.yaml
- data/companies/theguardian/property_data.yaml
- defaults/organization-defaults.yaml
- defaults/property-defaults.yaml
- scope3_methodology/api/api.py
- scope3_methodology/api/input_models.py
- scope3_methodology/cli/model_corporate_emissions.py
- scope3_methodology/cli/model_publisher_emissions.py
- scope3_methodology/corporate/model.py
- scope3_methodology/publisher/model.py
- scope3_methodology/test/test_api.py
- templates/organization/generic.yaml
- templates/property/display-app.yaml
- templates/property/display-generic.yaml
- templates/property/display-web.yaml
- templates/property/streaming-generic.yaml
- templates/property/streaming-video.yaml
Consolidate and move revenue allocation of corporate emissions due to digital emissions to be at the organization level 
```
➜ ./scope3_methodology/cli/model_corporate_emissions.py publisher data/companies/theguardian/corporate.yaml
digital_ads_allocation_corporate_emissions_g_co2e_per_month: 223192166.000000000
revenue_allocation_to_digital_ads_pct: 14.900000000
total_corporate_emissions_g_co2e_per_month: 1497934000.000000000
➜ ./scope3_methodology/cli/model_publisher_emissions.py --corporateEmissionsG 223192166  data/companies/theguardian/property_data.yaml
properties:
- client_device_emissions_g_co2e_per_imp: 0.067987302
corporate_emissions_g_co2e_per_impression: 0.018965959
data_transfer_electricity_kwh: 0.000010074
identifier: theguardian.com
impressions: 11768040000.000000000 …
```
> Update Corporate Emissions Model

- poetry.lock
@EmmaLouise2018 this pops a warning which I didn't dig into, just noticed we're hitting a security issue that we should prob fix
> update fastapi to 0.95 to fix security issue

- docs/cookie_sync_model.mdx
- docs/creative.mdx
- docs/publisher_model.mdx
Since the move to Mintlify, most links to other documentation pages were broken. I fixed these through this PR.
> Fixed various broken links to other documentation pages

- scope3_methodology/corporate/model.py
If we are given corporate emissions mt per month we do not require employees to be set.
> fix: allow for corporate emissions calculation without employees

- scope3_methodology/api/response_models.py
Update API response serialize decimals as decimal rather than a string. Docs: https://docs.pydantic.dev/latest/api/standard_library_types/#decimaldecimal 
Before 
After
> Fix API response model decimal serialization

- defaults/docs-defaults.yaml
- docs/calculations.mdx
- docs/snippets/defaults_ad_platform.mdx
- docs/snippets/defaults_consumer_device.mdx
- docs/snippets/defaults_conventional_model.mdx
- docs/snippets/defaults_device_size.mdx
- docs/snippets/defaults_media_size.mdx
- docs/snippets/defaults_power_model.mdx
- docs/snippets/defaults_video_player.mdx
- scope3_methodology/test/test_api.py
Creatives and ad formats have 0 or more ad tech platforms (ad server, brand safety, etc) on each request.
Update ad platform to include RTDP requests and simplify emissions calcs.
Clean up formatting on snippets
> Add ATP vendor calls to ad format and creative

- docs/calculations.mdx
Edits:
- `baseload_watts_per` -> `baseload_watts` 
- Moving `power_watts` before the `creative_data_transfer_usage_emissions_gco2pm` calculation just reads more logically
> Minor docs updates

- defaults/docs-defaults.yaml
- docs/snippets/defaults_conventional_model.mdx
There was a unit conversion error when copying the defaults from the [sri methodology file](https://github.com/SRISyndicatRegiesInternet/SRIxAD-DigitalCampaignsCarbonFramework/releases/download/v2.1.0/Referentiel.SRI.x.AD.-.V2.1_partage.zip).
The numbers for embodied emissions per byte of data transfer were off by a factor of a thousand, the number given in the SRI methodology for fixed network is 4.43 E-9 kg/kb which converts to 4.43 E-6 g/kb, the number in our methodology page was 4.43 E-3 so a thousand times that. THe error was probably caused from a weird phrasing in the methodology file where the unit is clearly specified as kg/kb but the origin field says it comes from the ADEME_220830_v1.4 number for emissionf per GB of data transfer, the french version of the file explicitly says …
> bug:Fixed network embodied emissions defaults

- defaults/docs-defaults.yaml
- docs/snippets/defaults_ad_platform.mdx
- scope3_methodology/test/test_api.py
Added the value for our generic ad server, Niki and I decided to go with the value we had previously calculated for private ad servers for now and maybe switch to the 80th percentile of ad servers once we have a more representative sample, the logic is as in: https://www.notion.so/scope3/Add-generic-ad-server-to-all-containers-ca86e9376426432c85f1708a343eaa0e?pvs=4
> Added generic ad server emissions default

- defaults/docs-defaults.yaml
- docs/calculations.mdx
- docs/snippets/defaults_channel_mapping.mdx
- docs/snippets/defaults_conventional_model.mdx
- docs/snippets/defaults_network_traffic.mdx
- scope3_methodology/test/test_api.py
Two minor updates resulting from today's discussion in the API V2 stand up:
- Removed the language and defaults around using fixed network as the fallback for tvs, pcs and smartspeakers. Rationalle is that those considerations are already embodied in the per country mix and while in the US most home usage (wifi) uses a fixed network in the developing world and rural areas it is often the case that home internet uses a mobile network infrastructure (either satelite or cellular).
- Updated the embodied emissions for data transfer for scope3 (previously 0) to match the numbers estimated by the SRI methodology.  
@ohalushchak-exadel tagging you here so I make sure not to deploy this without your api changes having been deployed (since this would break if you're expecting the …
> feat: No network default yes emboddied emissions

- defaults/docs-defaults.yaml
- docs/snippets/defaults_channel_mapping.mdx
- docs/snippets/defaults_video_player.mdx
streaming video defaults to the same as ctv-bvod to support enum transition from one to the other.
> feat: added defaults for streaming-video

- docs/calculations.mdx
This PR includes three changes to make sure the methodology is consistent:
1. Correct the conversion rate of bytes to kb (was using the kib conversion) basically change 1024 to 1000 in all conversions
2. Calculate bytes_per_imp directly from bytes_per_session and imps_per_session for clarity (old method was confusing because it went all the way to bytes_per_session_sec just to divide by secs again, this is what had resulted in the bug we saw this morning)
3. Add embodied network emissions to the data transfer emissions for ad selection
> fix: fix kb conversion and clarify kb per imp

- defaults/docs-defaults.yaml
- docs/calculations.mdx
- docs/snippets/defaults_ad_platform.mdx
- docs/snippets/defaults_channel_mapping.mdx
- scope3_methodology/test/test_api.py
Modified the defaults to have the right units and changed the inconsistent name of the bytes per session default. Left the old names in place for transition, will remove them once the api has been deployed to use the new ones. Changed the values in the bytes per session second to be consistent.
> fix: updated default names

- defaults/docs-defaults.yaml
- docs/snippets/defaults_ad_platform.mdx
- docs/snippets/defaults_channel_mapping.mdx
- scope3_methodology/test/test_api.py
For audio + CTV we use the bit rate by device, so no need to have the bytes per session as a default.
For the default bytes per sessions, focusing on the default bytes per session _second_. Also, updating these values to be in line with that current defaults used in the scope3 model.
Also, finishing the renaming of fields to be clear when a value is per imp vs per 1000 imp.
> fix: align defaults with original quality imps per second and content bytes per imp

- defaults/docs-defaults.yaml
- docs/snippets/defaults_channel_mapping.mdx
- scope3_methodology/test/test_api.py
Expose the default ad format based on unique identifier.
> Add in default ad format identifier by channel

- defaults/docs-defaults.yaml
- docs/snippets/defaults_channel_mapping.mdx
Revising the social defaults to be in line with the model updates to the core platforms.
- default data transfer kb comes down to more in line in app (slightly higher, but not as high as before)
- default media distribution corporate emissions goes up. we need to come back to review the the default corporate emissions of the other channels
> fix: Social defaults

- defaults/docs-defaults.yaml
- docs/snippets/defaults_channel_mapping.mdx
Make sure to have an exhaustive list of the channels in the default channel by device mapping. Importantly, make sure TV device supports social and audio channels (which are present in most TV app stores).
> fix: include all channels in default mappings

- defaults/docs-defaults.yaml
- docs/snippets/defaults_ad_platform.mdx
- scope3_methodology/test/test_api.py
Adding ad server defaults by channel rather than having a single adserver default that is used for all channels.
Starting with a specific social adserver default as we now have better numbers on the emissions associated with social adserving.
> adserver defaults by channel

- defaults/docs-defaults.yaml
- docs/calculations.mdx
- docs/snippets/defaults_ad_platform.mdx
- docs/snippets/defaults_channel_mapping.mdx
1- Added "streaming-video" (OLV) in channel definition.
2- Added default_consumer_device_request_size_bytes for "streaming-video" (OLV).
3- Ensured channel identification can default to "streaming-video" (OLV).
> Minor updates for OLV support

- docs/inference.mdx
- docs/training.mdx
Some minor improvements to the AI preview methodology docs.
* Fixed the multiplier on the Training page from 1.45 to 2.45 and added a tiny bit more explanation
* Added in divide-by-N for the PCR calculation in the amortization table in the Training page
* Removed the unnecessary division by sum(duration) for embodied emissions on the Inference Service page
* Used idle_power_gpu directly instead of E(0,0) / sum(duration) on the Inference Service page, which should be more clear
> Minor ai meth docs updates

- docs/ad_tech_model.mdx
- docs/api.mdx
- docs/calculations.mdx
- docs/consumer_devices.mdx
- docs/corporate_model.mdx
- docs/creative.mdx
- docs/data_quality.mdx
- docs/data_transfer.mdx
- docs/digital_out_of_home.mdx
- docs/lifecycle.mdx
- docs/property_metrics.mdx
- docs/publisher_model.mdx
The [https://methodology.scope3.com/llms.txt](https://methodology.scope3.com/llms.txt) is `null` for all titles. I couldn't test locally, but my guess is because the metadata is missing. This PR will add the metadata titles for each page
> docs: add pages title metadata

- defaults/docs-defaults.yaml
- docs/snippets/defaults_ad_platform.mdx
- docs/snippets/defaults_channel_mapping.mdx
- scope3_methodology/test/test_api.py
Spec: https://www.notion.so/scope3/Search-API-206680a89cf4803b89d3dbb254ae0e08
> feat: add search defaults
