scope3data/methodology

- .github/workflows/defaults_release.yaml
Notion Spec Link: https://www.notion.so/scope3/Part-II-Tech-Spec-ceb640f36d944cbd9a6febf75524acbb#f2f19386f076469cb0032cd673a8d011 
This will create a release like the following
> Add workflow to create a release with defaults on manual trigger

- README.md
- docs/corporate.md
- poetry.lock
- scope3_methodology/corporate.py
This reverts commit 6efc9c8a686961160fcfbf944748f4dc4a273682, reversing changes made to 45594a320c8796f7a71f68b3231ab51c36f84b02.
> Revert "Merge pull request #15 from scope3data/update_corporate"

- docs/corporate.md
- docs/datacenters.md
- poetry.lock
- sources/companies/google/data.yaml
- sources/research/boavizta/data.yaml
Benjamin assessment: https://docs.google.com/document/d/1in-l5SA2i472Ik48akjrBDgOdK6971wV_pLOWAAR77U/edit#
> incorporate feedback from benjamin davy

- data/companies/generic/atp_data.yaml
- data/private/scope3/8c32df930283f9a3203ae411c72e3f69/data.yaml
- data/private/scope3/d41d8cd98f00b204e9800998ecf8427e/data.yaml
One bug in field name, one new data set
> Update some of our private contributed data to make numbers make more sense

- data/companies/rea_group/corporate.yaml
This is my first push, to add a new yaml corporation file for REA Group
> Added new yaml file for REA Group Corporation.

- scope3_methodology/api/api.py
- scope3_methodology/test/defaults/atp-defaults.yaml
- scope3_methodology/test/defaults/end_user_device-defaults.yaml
- scope3_methodology/test/defaults/organization-defaults.yaml
- scope3_methodology/test/defaults/property-defaults.yaml
- scope3_methodology/test/test_api.py
- scope3_methodology/test/test_end_user_device_model.py
Resolve: https://github.com/scope3data/methodology/issues/66
> Issue 66: Streamline API startup data load and add test

- defaults/networking-defaults.yaml
- scope3_methodology/api/api.py
- scope3_methodology/api/input_models.py
- scope3_methodology/cli/compute_defaults.py
- scope3_methodology/cli/model_networking_emissions.py
- scope3_methodology/networking/__init__.py
- scope3_methodology/networking/model.py
- scope3_methodology/test/test_api.py
- scope3_methodology/test/test_networking_connection_model.py
- scope3_methodology/utils/custom_base_model.py
- templates/networking/fixed.yaml
- templates/networking/mobile.yaml
- templates/networking/unknown.yaml
Based on https://github.com/scope3data/methodology/blob/main/docs/data_transfer.md
> Add initial Networking bandwidth power usage model

- README.md
- defaults/property-defaults.yaml
- scope3_methodology/publisher/model.py
- templates/property/display-app.yaml
- templates/property/display-generic.yaml
- templates/property/display-web.yaml
- templates/property/streaming-generic.yaml
- templates/property/streaming-video.yaml
Compute scripts and publisher scripts complete without errors.
> Fix model publisher cli, pull optional constants into default files for visibility.

- .pre-commit-config.yaml
> Updated pre commit hook to run unit test

- docs/data_transfer.md
Per https://github.com/scope3data/methodology/issues/91
> add 5G/4G/3G data, don't update coefficients

- README.md
- data/companies/dpg_media/corporate.yaml
- defaults/atp-defaults.yaml
- defaults/end_user_device-defaults.yaml
- defaults/networking-defaults.yaml
- defaults/organization-defaults.yaml
- defaults/property-defaults.yaml
- defaults/transmission_rate-defaults.yaml
- scope3_methodology/test/test_api.py
Created folder for DPG Media and corporate.yaml file.
> Publishing DPG corporate sustainability numbers

- data/companies/nine_entertainment/corporate.yaml
- defaults/organization-defaults.yaml
- scope3_methodology/test/test_api.py
Adding new folder and corporate.yaml file for Nine Entertainment.
> Publishing Nine corporate sustainability numbers

- docs/mint.json
> docs: add github anchor to the documentation

- defaults/networking-defaults.yaml
- defaults/property-defaults.yaml
- defaults/transmission_rate-defaults.yaml
- scope3_methodology/test/test_api.py
- templates/property/digital-audio.yaml
updated quality_impressions_per_duration_s for digital-audio to match streaming-video.
> digital-audio quality_impressions_per_duration_s update

- docs/publisher_model.mdx
Switch to use terminology "Corporate Emissions"
> docs: docs update

- scope3_methodology/ad_tech_platform/model.py
Fix the ad tech platform computation when cookie sync information is `0`.  Verify that the denominator is valid before dividing by `0`
Given the input:
```
{
"atp_template": "ssp",
"allocation_of_corporate_emissions_pct": null,
"corporate_emissions_g_co2e": null,
"bid_requests_processed_from_ad_tech_platforms_pct": 1.15,
"bid_requests_processed_from_publishers_pct": 100,
"bid_request_size_in_bytes": 10000,
"server_to_server_emissions_g_co2e_per_gb": 1.379,
"server_emissions_mt_co2e_per_month": 0.0001,
"servers_processing_bid_requests_pct": 100,
"cookie_syncs_processed_per_bid_request": 0,
"datacenter_water_intensity_h2o_m_3_per_mwh": 17.1,
"server_emissions_g_co2e_per_kwh": 84.4,
"servers_processing_cookie_syncs_pct": 0,
"cookie_sync_distribution_ratio": 0, …
```
> Fix ad tech platform computation

- .github/workflows/build.yaml
> Update build.yaml for node@20

- docs/calculations.mdx
- Making docs clearer
- Fixing some missing unit conversions
- Removing some unnecessary unit conversions
> fix: creative calculations

- .github/workflows/deploy_website.yaml
Adding a github action to deploy when merging
> feat: add github action to deploy on merge

- .github/workflows/deploy_website.yaml
Added all the required parameters that were passed on the CLI previously
Failure from previous build: https://github.com/scope3data/methodology/actions/runs/8441256682/job/23119997690
> fix: use the right deploy command

- defaults/docs-defaults.yaml
- docs/calculations.mdx
- docs/snippets/defaults_channel_mapping.mdx
- docs/snippets/defaults_network_traffic.mdx
- scope3_methodology/test/test_api.py
Specified our methodology for choosing network or network mix and added default network per device for pc, tv and speakers
> feat: add default network 

- docs/creative.mdx
Updated Creative methodology to recognize changes made in the new model ad formats feature.
> Update model custom ad formats methodology.mdx

- docs/calculations.mdx
Updating calculation examples to pull 3p served out of ad format model and demonstrate that it is a reporting api input
> Update calculations 3p served

- docs/calculations.mdx
@pymble2073 Added using the property video bitrate in https://github.com/scope3data/methodology/pull/222. Updating a missed location in the docs.
> Updating Calculations

- defaults/docs-defaults.yaml
- docs/snippets/defaults_channel_mapping.mdx
Updated default ad format and device for new OLV channel
> Updated default ad format and device for new OLV channel

- docs/mint.json
> feat: add link to preview from the main site

- docs/data_quality.mdx
https://www.notion.so/scope3/Update-methodology-docs-191680a89cf4808ebbccca83293f17a1
> chore: Methodology docs - intro & ad platform

- docs/calculations.mdx
- docs/consumer_devices.mdx
- docs/corporate_model.mdx
- docs/data_quality.mdx
- docs/digital_out_of_home.mdx
Fix the links reported by `mintlify broken-links` command
> fix: docs broken links

- docs/channel_considerations.mdx
- docs/mint.json
> fix: channels consideration -> channel considerations

- docs/channel_considerations.mdx
> tiny fixes to methodology docs pages
